caex.CurrencyName AS CurrencyExtraIncomeName,
caad.CurrencyName AS CurrentcyAdvanceSalaryName,
cacs.CurrencyName AS CurrencyContractSalaryName,
cnea.NameEntityName as DigitalSignatureCodeName,
hct.tempFormCompSalary,
hct.JobLevel,
hct.LevelAgencyID,
hct.CooperationRate,
hct.FileAttachmentSal,
hct.ExtraIncome,
hct.AdvanceSalary,
hct.ContractSalary,
hct.E_ExtraIncome,
hct.E_AdvanceSalary,
hct.E_ContractSalary,
hct.ReEvaluatateRemark,
doc.DeclineReason AS ReasonRefusalApplication,
hpreject.ProfileName as UserRejectName,
hpcancel.ProfileName as UserCancelName,
ccnew.ContractTypeName as NewNextContractTypeName,
unitnew.EnumTranslate AS UnitTimeNextContractTypeName,
slary.SalaryClassName as SalaryClassNameTL,
cct.ContractTypeName as ContractTypeNameNext,
cne4.NameEntityName as TermsOfContractName,
cawt.WorkPlaceName as WorkPlaceTranslateName,
exPro.ProfileName as ExProfileSingName,
exPro.NameEnglish as ExProfileSingNameEN,
exPos.PositionName as ExPositionSingName,
exPos.PositionEngName as ExPositionSingNameEN,
exwl.WorkPlaceName as ExWorkPlaceTranslateName,
cat2.AbilityTitleVNI as ExAbilityTitleVNI,
cat2.AbilityTitleEng as ExAbilityTitleEng,
cp2.ProvinceName as ProfilePProvinceName,
cp2.ProvinceNameEN as ProfilePProvinceNameEN,
cd2.DistrictName as ProfilePDistrictName,
cd2.DistrictNameEN as ProfilePDistrictNameEN,
cv2.VillageName as ProfileVillageName,
cv2.VillageNameEN as ProfileVillageNameEN,
Conttype.Code as ContractTypeCodeView,
cpg.PayrollGroupName as PayrollGroupName,
cpg.Code as PayrollGroupCode,
cne.OtherName as AnotherNameofAcademicLevel,
ccp.CompanyName,
ccp.CompanyNameEN,
ccp.AddressVN as AddressVN_Company,
ccp.AddressEN as AddressEN_Company,
ccp.Phone,
ccp.Image,
ccp.Image asCompanyLogo,
ccp.ShortName,
ccp.ChairmanNameVN,
ccp.ChairmanNameEN,
ccp.ChairmanNationalityVN,
ccp.ChairmanNationalityEN,
ccp.ChairmanJobtitileVN,
ccp.ChairmanJobtitleEN,
ccp.ChairmanPositionVN,
ccp.ChairmanPositionEN,
ccp.ChairmanGender,
ccp.ProfileNameSing,
ccp.Code as Code_Company,
cgv.EnumTranslate as ChairmanGenderView,
ccp.DateOfBirthSing,
ccp.PlaceOfBirthSing,
ccp.PositionNameSing,
ccp.JobTitleNameSing,
ccp.IDNoSing,
ccp.IDDateOfIssueSing,
ccp.IDPlaceOfIssueSing,
ccp.PAddressSing,
Temp.PITCode,
ptv.EnumTranslate as PITCodeView,
cou.E_COMPANY,
cou.E_BRANCH,
cou.E_UNIT,
cou.E_DIVISION,
cou.E_DEPARTMENT,
cou.E_TEAM,
cou.E_SECTION,
cou.E_OU_L8,
cou.E_OU_L9,
cou.E_OU_L10,
cou.E_OU_L11,
cou.E_OU_L12,
cou.E_COMPANY_CODE,
cou.E_BRANCH_CODE,
cou.E_UNIT_CODE,
cou.E_DIVISION_CODE,
cou.E_DEPARTMENT_CODE,
cou.E_TEAM_CODE,
cou.E_SECTION_CODE,
cou.E_OU_L8_CODE,
cou.E_OU_L9_CODE,
cou.E_OU_L10_CODE,
cou.E_OU_L11_CODE,
cou.E_OU_L12_CODE,
cou.OrgParent1,
cou.OrgParent2,
cou.OrgParentCode1,
cou.OrgParentCode2,
cou.OrgParentEN1,
cou.OrgParentEN2,
cou.E_COMPANY_E,
cou.E_BRANCH_E,
cou.E_UNIT_E,
cou.E_DIVISION_E,
cou.E_DEPARTMENT_E,
cou.E_TEAM_E ,
cou.E_SECTION_E,
crio.RegionName,
cc1.CurrencyName as CurrencySalName,
cc2.CurrencyName AS CurenncyInsName,
cc3.CurrencyName AS CurenncyAllowance1Name,
cc4.CurrencyName AS CurenncyAllowance2Name,
cc5.CurrencyName AS CurenncyAllowance3Name,
cc6.CurrencyName AS CurenncyOAllowanceName,
cc7.CurrencyName AS CurenncyAllowance4Name,
sv.EnumTranslate as StatusView,
hp1.ProfileName AS ProfileSingName,
hp1.NameEnglish AS ProfileSingNameEN,
hp1.DateOfBirth as ProfileSingDateOfBirth,
hp1.IDNo as ProfileSingIDNo,
hp1.IDPlaceOfIssue as ProfileSingIDPlaceOfIssue,
hp1.IDDateOfIssue as ProfileSingIDDateOfIssue,
hp1.PAddress as ProfileSingPAddress,
hp1.Gender AS ProfileSignGender,
cq.QualificationName,
cq.QualificationName as QualificationNameContract,
cq.Code as QualificationCodeContract,
csc1.SalaryClassName as ClassRateName,
csc1.SalaryClassName,
csct1.SalaryClassTypeName,
csr1.SalaryRankName AS RankRateName,
csr1.Rate as RankRateIDRate,
csr1.SalaryMin,
csr1.SalaryMax,
csr1.code as PayRankCode,
cua1.UsualAllowanceName AS AllowanceID1Name,
cua2.UsualAllowanceName AS AllowanceID2Name,
cua3.UsualAllowanceName AS AllowanceID3Name,
cua4.UsualAllowanceName AS AllowanceID4Name,
cua5.UsualAllowanceName AS AllowanceID5Name,
cua6.UsualAllowanceName AS AllowanceID6Name,
cua7.UsualAllowanceName AS AllowanceID7Name,
cua8.UsualAllowanceName AS AllowanceID8Name,
cua9.UsualAllowanceName AS AllowanceID9Name,
cua10.UsualAllowanceName AS AllowanceID10Name,
cua11.UsualAllowanceName AS AllowanceID11Name,
cua12.UsualAllowanceName AS AllowanceID12Name,
cua13.UsualAllowanceName AS AllowanceID13Name,
cua14.UsualAllowanceName AS AllowanceID14Name,
cua15.UsualAllowanceName AS AllowanceID15Name,
hce.Note2 As ContractExtendNote2,
hce.Note As ContractExtendNote,
cua1.IsInsurrance as IsInsurranceAllowance1,
cua2.IsInsurrance as IsInsurranceAllowance2,
cua3.IsInsurrance as IsInsurranceAllowance3,
cua4.IsInsurrance as IsInsurranceAllowance4,
cua5.IsInsurrance as IsInsurranceAllowance5,
cua6.IsInsurrance as IsInsurranceAllowance6,
cua7.IsInsurrance as IsInsurranceAllowance7,
cua8.IsInsurrance as IsInsurranceAllowance8,
cua9.IsInsurrance as IsInsurranceAllowance9,
cua10.IsInsurrance as IsInsurranceAllowance10,
cua11.IsInsurrance as IsInsurranceAllowance11,
cua12.IsInsurrance as IsInsurranceAllowance12,
cua13.IsInsurrance as IsInsurranceAllowance13,
cua14.IsInsurrance as IsInsurranceAllowance14,
cua15.IsInsurrance as IsInsurranceAllowance15,
cne3.NameEntityName AS VehicleName,
cne2.NameEntityName as CostSourceName,
cne1.NameEntityName AS GraduatedLevelName,
cne.NameEntityName AS EducationLevelName,
cne10.NameEntityName AS NationalityGroup,
cwp.WorkPlaceName,
cwp.[Address] as AddressWorkPlace,
cwp.[Description] as DescriptionWorkPlace,
EmployeeGroup.NameEntityName as EmployeeGroupName,
cne5.NameEntityName as ReasonChangeSalaryName,
cne6.NameEntityName as ReasonChangeSalaryName2,
cne7.NameEntityName as DelegationReasonName,
cne50.NameEntityName as DelegationReasonName2,
cet.EmployeeTypeName,
cpf.PITFormulaName,
ccy.CountryName AS NationalityName,
ccy.CountryNameES as NationalityNameEn,
ccy1.CountryName as TCountryName,
ccy2.CountryName as PCountryName,
cp1.ProvinceName as TProvinceName,
cp2.ProvinceName as PProvinceName,
cd1.DistrictName as TDistrictName,
cd2.DistrictName as PDistrictName,
cv1.VillageName as TVillageName,
cv2.VillageName as PVillageName,
co1.OrgStructureName as OrgStructureParent,
co1.OrgStructureName as ParentIDOrgStructureName,
coio.Info1,
coio.Info2,
coio.Info3,
coio.Info4,
coio.Info5,
coio.Info6,
coio.Info7,
coio.Info8,
coio.Info9,
coio.Info10,
coio.Info11,
coio.Info12,
coio.Info13,
coio.Info14,
cj1.Jobtitlename as ProfileSingJobtitlename,
cj1.JobtitlenameEn as ProfileSingJobtitlenameEN,
cp11.Positionname as PositionProfileSign,
cp11.PositionEngName AS PositionEngNameProfileSign,
ccty.CountryName AS ProfileSingNationalityName,
ccty.CountryNameES AS ProfileSingNationalityNameEN,
cpprosing.ProvinceName as ProfileSingPProvinceName,
cdprosing.DistrictName as ProfileSingPDistrictName,
cvprosing.VillageName as ProfileSingPVillageName,
cmibranch.BillingAddress as BranchBillingAddress,
cmibranch.TelePhone as BranchTelePhone,
orgCompany.BillingAddress,
orgCompany.TelePhone as TelePhoneOrg,
Delegate.NoDecision as DelegateCompanyNoDecision,
DelegatePro.ProfileName as DelegateCompanyProfileName,
DelegatePro.IDNo as DelegateCompanyIDNo,
DelegatePro.IDDateOfIssue as DelegateCompanyIDDateOfIssue,
DelegatePro.IDPlaceOfIssue as DelegateCompanyIDPlaceOfIssue,
DelegatePos.PositionName as DelegateCompanyPositionName,
hp2.ProfileName AS Supervisor,
hp2.ProfileName AS SupervisorName,
highSup.profilename as HighSupervisorName,
crr.ResignReasonName,
cga.GradeAttendanceName,
cga.Code as GradeAttendanceCode,
performanceTemplate.TemplateName,
egv.EnumTranslate as GenderView,
utv.EnumTranslate as UnitTimeView,
tcv.EnumTranslate as TypeView,
tcv.EnumTranslate as TypeContractType,
ssv.EnumTranslate as StatusSynView,
csv.EnumTranslate AS ContractStatusView,
sev.EnumTranslate AS StatusEvaluationView,
contractJob.JobTitleName,
contractJob.Code as JobTitleCode,
ccc1.CostCentreName,
cw1.WorkPlaceName,
contractJob.JobTitleNameEn,
contractPos.PositionName,
contractPos.Code AS PositionCode,
contractPos.NumberOfChangeJobDescription,
contractPos.EffectiveDateOfDescription,
cwp.Code as WorkPlaceCode,
cust.UnitName,
cust.UnitCode,
lt.EnumTranslate as LaborTypeView,
EnumWorkTimeInWeekType.EnumTranslate as WorkTimeInWeekView,
EnumCalendarWorkType.EnumTranslate as CalendarWorkView,
EnumWeeklyLeaveDayType.EnumTranslate as WeeklyLeaveDayView,
contractpos.PositionEngName,
cpt.PositionOtherName,
cpt.Requirement as PositionRequirement,
cpt.Permission as PositionPermission,
cpt.TaskShortTerm as PositionTaskShortTerm,
cpt.TaskLongTerm as PositionTaskLongTerm,
hpmi.LastNameEN,
hpmi.FirstNameEN,
hpmi.MiddleNameEN,
contractJob.Notes as NotesJobTitle,
cn.NameEntityName as DistributionChannelName,
cn1.NameEntityName as MarketDomainName,
cn2.NameEntityName as RegionMarketName,
cn3.NameEntityName as MarketAreaName,
cn4.NameEntityName as OriginalDistributorName,
curkpi.CurrencyName as CurrencyKPIName,
kpirank.KPIRankName,
hpmiProvince.ProvinceName as ProvinceBirthName,
hpmiDistrict.DistrictName as DistrictBirthName,
hpmiVillage.VillageName as VillageBirthName,
cuap.UsualAllowanceGroupName,
scv.EnumTranslate as ContractEvaType,
tofp.EnumTranslate as TypeOfPassView,
SignatureDigitalStatus.EnumTranslate as StatusEmailSignatureDigitalView,
curtotal.currencyname as TotalSalaryCurrencyName,
curtotal2.currencyname as TotalAllowanceCurrencyName,
contractTCountry.countryName as ContractTCountryName,
contractTProvince.ProvinceName as ContractTProvinceName,
contractTDistrict.DistrictName as ContractTDistrictName,
contractTVillage.VillageName as ContractTAVillageName,
ccp.Note as CompanyNote,
E_COMPANYOther.OrgStructureOtherName as E_COMPANYOrgStructureOtherName,
E_BRANCHOther.OrgStructureOtherName as E_BRANCHOrgStructureOtherName,
E_UNITOther.OrgStructureOtherName as E_UNITOrgStructureOtherName,
E_DIVISIONOther.OrgStructureOtherName as E_DIVISIONOrgStructureOtherName,
E_DEPARTMENTOther.OrgStructureOtherName as E_DEPARTMENTOrgStructureOtherName,
E_TEAMOther.OrgStructureOtherName as E_TEAMOrgStructureOtherName,
E_SECTIONOther.OrgStructureOtherName as E_SECTIONOrgStructureOtherName,
proqua.QualificationName as QualificationNameMain,
proqua.TrainingPlace as TrainingPlaceMain,
proqua.FieldOfTraining as FieldOfTrainingMain,
ttProSal.CurrencyName AS TotalProbationaryCurrencyName,
dbo.fcDocsothanhchu(hct.TotalProbationarySalary)  as TotalProbationarySalaryFormat,
dbo.fcDocsothanhchu_EN(hct.TotalProbationarySalary)  as TotalProbationarySalaryFormatEN,
dbo.fcDocsothanhchu(hct.TotalSalary)  as TotalSalaryFormat,
dbo.fcDocsothanhchu_EN(hct.TotalSalary)  as TotalSalaryFormatEN,
cai.IDCardIssuePlaceEngName as IDCardPlaceOfIssueNameEng,
capp.PassportIssuePlaceEngName as PassportPlaceOfIssueNameEng,
cc.ValueTime,
cc.UnitTime,
cc.Type,
sui.UserInfoName as UserApproveIDEvaName,
sui2.UserInfoName as UserApproveIDEva2Name,
sui3.UserInfoName as UserApproveIDEva3Name,
sui4.UserInfoName as UserApproveIDEva4Name,
hct.DateEndProbation as ContractDateEndProbation,
hp.StatusSyn,
hct.DecisionNo,
hct.VNSalary,
hct.TermsOfContractID,
hct.VNENSalary,
hct.JapanSalary,
hct.JapanVNSalary,
hct.TextLink,
hct.ContractEvaType,
hct.TypeOfPass,
hct.GradeAttendanceID,
hct.WorkPlaceID,
hct.PayrollGroupID,
hct.ID,
hct.E_IDNo,
hct.E_PassportNo,
hct.DateStartProbation,
hct.DateEndProbation,
hct.ProbationTimeUnit,
hct.ProbationTime,
utv3.EnumTranslate as ProbationTimeUnitName,
hct.NewNextContractTypeID,
hct.DateStartNextContractType,
hct.DateEndNextContractType,
hct.DurationNextContractType,
hct.UnitTimeNextContractType,
hp.E_IDCard as E_ProfileIDCard,
hct.Note,
hct.Code,
hct.Status,
hct.ContractTypeID,
hct.ContractNo,
hct.DateSigned,
hct.DateStart,
hct.DateEnd,
hct.JobTitleID,
hct.DateOfContractEva,
hct.EvaluationResult,
hct.ContractResult,
hct.Behaviour,
hct.Competence,
hct.DateStartNextContract,
hct.DateEndNextContract,
hct.NextContractTypeID,
hct.Remark,
hct.RankDetailForNextContract,
hct.PositionID,
hct.ProfileID,
hct.EmployeeGroupID,
hct.DateCreate,
hct.DateUpdate,
hct.IPCreate,
hct.StatusEvaluation,
hct.IPUpdate,
hct.FollowNo,
hct.ProfileSingID,
hct.PersonalRate,
hct.FormPaySalary,
hct.QualificationID,
hct.HourWorkInMonth,
hct.DateAuthorize,
hct.ClassRateID,
hct.RankRateID,
hct.SalaryClassTypeID,
hct.DateExtend,
hct.Duration,
hct.Duration as DurationContract,
hct.CurenncyID,
hct.CurenncyID1,
hct.CurenncyID2,
hct.CurenncyID3,
hct.CurenncyIDSalary,
hct.CurenncyID5,
hct.CurenncyID4,
hct.AllowanceID1,
hct.AllowanceID2,
hct.ContractStatus,
hct.AllowanceID3,
hct.AllowanceID4,
hct.AllowanceID5,
hct.AllowanceID6,
hct.AllowanceID7,
hct.AllowanceID8,
hct.AllowanceID9,
hct.AllowanceID10,
hct.AllowanceID11,
hct.AllowanceID12,
hct.AllowanceID13,
hct.AllowanceID14,
hct.AllowanceID15,
hct.NoPrint,
hct.Salary,
hct.NextSalary,
hct.NextInsuranceAmount,
hct.InsuranceAmount,
hct.Allowance1,
hct.Allowance2,
hct.Allowance3,
hct.Allowance4,
hct.Allowance,
hct.Allowance5,
hct.Allowance6,
hct.Allowance7,
hct.Allowance8,
hct.Allowance9,
hct.Allowance10,
hct.Allowance11,
hct.Allowance12,
hct.Allowance13,
hct.Allowance14,
hct.Allowance15,
hct.E_Salary,
hct.E_NextSalary,
hct.E_NextInsuranceAmount,
hct.E_InsuranceAmount,
hct.E_Allowance,
hct.E_Allowance1,
hct.E_Allowance2,
hct.E_Allowance3,
hct.E_Allowance4,
hct.E_Allowance5,
hct.E_Allowance6,
hct.E_Allowance7,
hct.E_Allowance8,
hct.E_Allowance9,
hct.E_Allowance10,
hct.E_Allowance11,
hct.E_Allowance12,
hct.E_Allowance13,
hct.E_Allowance14,
hct.E_Allowance15,
hct.UserCreate,
hct.IsNotSignContinue,
hct.TerminateDate,
hct.CompanyID,
hct.ReasonChangeSalaryID,
hct.ReasonChangeSalaryID2,
hct.DelegationReasonID,
hct.DelegationReasonID2,
hct.TimesContract,
hct.EmployeeTypeID,
hct.AbilityTileID,
hct.DelegateCompanyID,
hct.OrgStructureID,
hct.EvaPerformanceTemplateID,
hct.WorkMorningTimeStart,
hct.WorkMorningTimeEnd,
hct.WorkAfternoonTimeStart,
hct.WorkAfternoonTimeEnd,
hct.AttachFile as Attachment,
cc.ContractTypeName,
cc.Code AS ContractTypeCode,
cc.Description AS ContractTypeDescription,
cc.ExportID,
cc.Description,
co.OrgStructureName,
co.AddressDetail,
co.Code AS OrgStructureCode,
co.OrgStructureOtherName,
co.OrgStructureNameEN,
co.OrgFullName,
catat.AbilityTitleVNI,
catat.AbilityTitleEng,
hp.CostSourceID,
hp.RegionID,
hp.EducationLevelID,
hp.CodeEmpClient,
hp.DatehireNew,
hp.DateApplyAttendanceCode,
hp.OrgStructureID as ProfileOrgStructureID,
hp.Gender,
hp.GraduatedLevelID,
hp.CodeEmp,
hp.ProfileName,
hp.PlaceOfBirth,
hp.IDPlaceOfIssue,
hp.IDDateOfIssue,
hp.DateOfBirth,
hp.IDNo,
hp.PAddress,
hp.DateHire,
hp.DateEndProbation as ProfileDateEndProbation,
hp.DateOfEffect,
hp.NameEnglish,
hp.PassportDateOfIssue,
hp.PassportDateOfExpiry,
hp.SocialInsNo,
hp.PlaceOfBirth as ProfilePlaceOfBirth,
dbo.fChuyenCoDauThanhKhongDau(hp.PAddress) as ProfilePAddressEN,
hp.SocialInsIssuePlace,
hp.SocialInsIssueDate,
hp.CodeTax,
hp.Permission,
hp.TaskShortTerm,
hp.TaskLongTerm,
hp.SikillLevel,
hp.AddressSecondaryEmergency,
hp.idcard as ProfileIDCard,
hp.IDCardDateOfIssue as ProfileIDCardDateOfIssue,
hp.IDCardPlaceOfIssue as ProfileIDCardPlaceOfIssue,
hp.Email,
hp.MonthOfBirth,
hp.YearOfBirth,
hp.Cellphone,
hp.DateQuit,
hp.PAddress as ProfilePAddress,
hp.IDNo as ProfileIDNo,
hp.IDDateOfIssue as ProfileIDDateOfIssue,
hp.IDPlaceOfIssue as ProfileIDPlaceOfIssue,
hp.SupervisorID,
hp.HighSupervisorID,
hp.ResReasonID,
hp.NationalityID,
hp.PCountryID,
hp.PProvinceID,
hp.PDistrictID,
hp.VillageID,
hp.VehicleID,
co.ParentID,
co.ID as CoID,
hp.DayOfBirth,
hp.EthnicID,
hp.UnitStructureID,
hct.DayOfAnnualLeave,
hct.ProbationSalary,
hct.E_ProbationSalary,
hct.LaborType,
hp.ProbationTime as ProfileProbationTime,
hp.ProfileMoreInfoID,
hct.DistributionChannelID,
hct.MarketDomainID,
hct.RegionMarketID,
hct.MarketAreaID,
hct.OriginalDistributorID,
hct.OtherDistributors,
hct.KPIRankID,
hct.CurrencyKPIID,
hct.KPIAmount,
hct.E_KPIAmount,
hct.SalaryPaidByTheFormOf,
hct.CoefficientOfWorkmanship,
hct.UsualAllowanceGroupID,
hp.DateSenior,
hp.SalaryClassID,
hct.TotalSalaryCurrencyID,
hct.TotalAllowanceCurrencyID,
hct.PassportPlaceOfIssue,
hct.PassportNo as ContractPassportNo,
hct.PassportPlaceOfIssue as ContractPassportPlaceOfIssue,
hct.PassportNo,
hct.TAddress,
hct.TAddressEN,
hct.PAddressEN,
hct.TAddress as ContractTAddress,
hct.TCountryID,
hct.TProvinceID,
hct.TDistrictID,
hct.TAVillageID,
hct.WorkTimeInWeek,
hct.CalendarWork,
hct.WeeklyLeaveDay,
hct.E_TotalSalary,
hct.E_TotalAllowance,
hct.E_TotalProbationarySalary,
hct.TotalProbationSalCurrencyID,
hct.StatusEmailSignatureDigital,
cpow.ProvinceName as ProvinceOfWork,
ctow.CountryName as CountryOfWork,
hct.ReasonReject,
hct.UserRejectID,
hct.DateReject,
hct.CancelReason,
hct.DateCancel,
hct.UserCancelID,
hct.BenefitLevel,
contractPosParent.PositionName as HeadPositionName,
cegsd2.EmpGroupSecondDetailName,
cegfd1.EmpGroupFirstDetailName,
cegsd4.EmpGroupSecondDetailName as EmpGroupSecondDetailNameContractExtand,
cegfd3.EmpGroupFirstDetailName as EmpGroupFirstDetailNameContractExtand,
cpPlaceOfIssue.ProvinceName AS PlaceOfIssueIDView,
cpIDCardIssuePlace.IDCardIssuePlaceName AS IDCardIssuePlaceIDView,
cpPassportPlace.PassportIssuePlaceName AS PassportPlaceIDView,
hct.StatusCancelDigitalSignature,
hct.ReasonCancel,
hct.PersonCancellationID,
PersonCancellation.ProfileName as PersonCancellationName,
statusCancelDigitalSignature.EnumTranslate as StatusCancelDigitalSignatureView,
cal.LevelAgencyName,
hct.DigitalSignatureCodeID,
cn5.NameEntityName as CostSourceIDName