
Hre_Contract hct
INNER JOIN Hre_Profile hp ON hct.ProfileID = hp.id
left JOIN $select id, isdelete, AbilityTitleVNI,AbilityTitleEng from Cat_AbilityTile$ catat  ON hct.AbilityTileID = catat.id AND catat.IsDelete IS NULL
left JOIN Cat_OrgStructure co  ON hct.OrgStructureID = co.id AND co.IsDelete IS NULL
Inner JOIN Cat_ContractType cc  ON hct.ContractTypeID = cc.id AND cc.IsDelete IS NULL
LEFT JOIN $select id from Cat_IDCardIssuePlace$ cai ON cai.IDCardIssuePlaceName = hp.IDCardPlaceOfIssue AND cai.IsDelete IS NULL
LEFT JOIN $select id from Cat_PassportIssuePlace$ capp ON capp.PassportIssuePlaceName = hp.PassportPlaceOfIssue  AND capp.IsDelete IS NULL
LEFT JOIN $select id, isdelete, ObjectID,EvaluationType,Status  from #tblEvaluationDocument$ hed ON hed.ObjectID = hct.ID AND hed.IsDelete IS NULL
LEFT JOIN $select id, isdelete, WorkPlaceName, [Address], [Description], Code, ProvinceID from Cat_WorkPlace$ cwp ON cwp.id = hct.WorkPlaceID AND cwp.IsDelete IS NULL
LEFT JOIN $select id, isdelete, ProvinceName, CountryID from Cat_Province$ cpow on cpow.ID = cwp.ProvinceID AND cpow.IsDelete IS NULL
LEFT JOIN $select id, isdelete, CountryName from Cat_Country$ ctow on ctow.ID = cpow.CountryID and ctow.IsDelete IS NULL
left join $select id, isdelete,ProfileID, UserInfoName from Sys_UserInfo$ sui   ON hct.UserApproveIDEva = sui.id AND sui.IsDelete IS NULL
left join $select id, isdelete,ProfileID, UserInfoName from Sys_UserInfo$ sui2  ON hct.UserApproveIDEva2 = sui2.id AND sui2.IsDelete IS NULL
left join $select id, isdelete,ProfileID, UserInfoName from Sys_UserInfo$ sui3  ON hct.UserApproveIDEva3 = sui3.id AND sui3.IsDelete IS NULL
left join $select id, isdelete,ProfileID, UserInfoName from Sys_UserInfo$ sui4  ON hct.UserApproveIDEva4 = sui4.id AND sui4.IsDelete IS NULL
Inner JOIN #tblPermission fcP ON fcP.Id = hct.id
LEFT JOIN $SELECT id, IsDelete, LevelAgencyName FROM Cat_LevelAgency$ cal ON cal.id = hct.LevelAgencyID AND cal.IsDelete IS NULL
LEFT JOIN $select id, isdelete,CurrencyName from Cat_Currency$ caex ON caex.id = hct.CurrencyExtraIncomeID AND caex.IsDelete IS NULL
LEFT JOIN $select id, isdelete,CurrencyName from Cat_Currency$ caad ON caad.id = hct.CurrentcyAdvanceSalaryID AND caad.IsDelete IS NULL
LEFT JOIN $select id, isdelete,CurrencyName from Cat_Currency$ cacs ON cacs.id = hct.CurrencyContractSalaryID AND cacs.IsDelete IS NULL
LEFT JOIN $select id, isdelete,ContractTypeName from Cat_ContractType$ ccnew ON hct.NewNextContractTypeID = ccnew.id AND ccnew.IsDelete IS NULL
LEFT JOIN #tblUnitType unitnew ON unitnew.EnumKey = hct.UnitTimeNextContractType
LEFT JOIN $select id from #Cat_Currency$ ttProSal ON ttProSal.id = hct.TotalProbationSalCurrencyID AND ttProSal.IsDelete IS NULL
LEFT JOIN $select ID, IsDelete, Code FROM Cat_ContractType$ Conttype ON Conttype.ID = hct.ContractTypeID AND Conttype.IsDelete IS NULL
LEFT JOIN Cat_Company ccp ON ccp.id = hct.CompanyID AND ccp.IsDelete IS NULL
LEFT JOIN #tblSalTax Temp ON hct.ProfileID = Temp.ProfileID
LEFT JOIN $select id, isdelete,PITFormulaName from Cat_PITFormula$ cpf on cpf.Id=Temp.PITFormulaID AND cpf.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName, Code from Cat_NameEntity$ cne4 ON cne4.id = hct.TermsOfContractID AND cne4.IsDelete IS NULL
LEFT JOIN $select id from #Cat_Currency$ cc1 ON cc1.id = hct.CurenncyID AND cc1.IsDelete IS NULL
LEFT JOIN $select id from #Cat_Currency$ cc2 ON cc2.id = hct.CurenncyID1 AND cc2.IsDelete IS NULL
LEFT JOIN $select id from #Cat_Currency$ cc3 ON cc3.id = hct.CurenncyID2 AND cc3.IsDelete IS NULL
LEFT JOIN $select id from #Cat_Currency$ cc4 ON cc4.id = hct.CurenncyID3 AND cc4.IsDelete IS NULL
LEFT JOIN $select id from #Cat_Currency$ cc5 ON cc5.id = hct.CurenncyIDSalary AND cc5.IsDelete IS NULL
LEFT JOIN $select id from #Cat_Currency$ cc6 ON cc6.id = hct.CurenncyID5 AND cc6.IsDelete IS NULL
LEFT JOIN $select id from #Cat_Currency$ cc7 ON cc7.id = hct.CurenncyID4 AND cc7.IsDelete IS NULL
left join $select E_COMPANY, E_BRANCH, E_UNIT, E_DIVISION, E_DEPARTMENT, E_TEAM, E_SECTION, E_OU_L8, E_OU_L9, E_OU_L10,E_OU_L11, E_OU_L12, E_COMPANY_CODE, E_BRANCH_CODE, E_UNIT_CODE, E_DIVISION_CODE, E_DEPARTMENT_CODE, E_TEAM_CODE, E_SECTION_CODE, E_OU_L8_CODE,E_OU_L9_CODE, E_OU_L10_CODE, E_OU_L11_CODE, E_OU_L12_CODE,OrgstructureID, IsDelete,OrgParent1,OrgParent2,OrgParentCode1,OrgParentCode2,OrgParentEN1,OrgParentEN2, E_COMPANY_E, E_BRANCH_E, E_UNIT_E, E_DIVISION_E, E_DEPARTMENT_E,E_TEAM_E , E_SECTION_E from Cat_OrgUnit$ cou ON hct.OrgstructureID = cou.OrgstructureID AND cou.IsDelete IS NULL
left join $select id from #tblOrgDistince$ E_COMPANYOther on E_COMPANYOther.Code = cou.E_COMPANY_CODE
left join $select id from #tblOrgDistince$ E_BRANCHOther on E_BRANCHOther.Code = cou.E_BRANCH_CODE
left join $select id from #tblOrgDistince$ E_UNITOther on E_UNITOther.Code = cou.E_UNIT_CODE
left join $select id from #tblOrgDistince$ E_DIVISIONOther on E_DIVISIONOther.Code = cou.E_DIVISION_CODE
left join $select id from #tblOrgDistince$ E_DEPARTMENTOther on E_DEPARTMENTOther.Code = cou.E_DEPARTMENT_CODE
left join $select id from #tblOrgDistince$ E_TEAMOther on E_TEAMOther.Code = cou.E_TEAM_CODE
left join $select id from #tblOrgDistince$ E_SECTIONOther on E_SECTIONOther.Code = cou.E_SECTION_CODE
LEFT JOIN $select id, isdelete, ProfileName,JobTitleID,PositionID,NationalityID, NameEnglish,DateOfBirth,IDNo,IDPlaceOfIssue,IDDateOfIssue,PAddress, YearOfBirth, gender,PprovinceID,PdistrictID,TAVillageID,VillageID, TAddress from Hre_Profile$ hp1 ON hp1.id = hct.ProfileSingID AND hp1.IsDelete IS NULL
LEFT JOIN $select id, isdelete,QualificationName, Code from Cat_Qualification$ cq ON cq.id = hct.QualificationID AND cq.IsDelete IS NULL
LEFT JOIN $select id, isdelete, SalaryClassName from Cat_SalaryClass$ csc1 ON csc1.id = hct.ClassRateID AND csc1.IsDelete IS NULL
LEFT JOIN $select id, isdelete, SalaryClassTypeName from Cat_SalaryClassType$ csct1 ON csct1.id = hct.SalaryClassTypeID AND csct1.IsDelete IS NULL
LEFT JOIN $select id, isdelete, SalaryRankName, SalaryMin, SalaryMax, Rate, code from Cat_SalaryRank$ csr1 ON csr1.id = hct.RankRateID AND csr1.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua1 ON cua1.id = hct.AllowanceID1 AND cua1.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua2 ON cua2.id = hct.AllowanceID2 AND cua2.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua3 ON cua3.id = hct.AllowanceID3 AND cua3.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua4 ON cua4.id = hct.AllowanceID4 AND cua4.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua5 ON cua5.id = hct.AllowanceID5 AND cua5.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua6 ON cua6.id = hct.AllowanceID6 AND cua6.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua7 ON cua7.id = hct.AllowanceID7 AND cua7.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua8 ON cua8.id = hct.AllowanceID8 AND cua8.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua9 ON cua9.id = hct.AllowanceID9 AND cua9.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua10 ON cua10.id = hct.AllowanceID10 AND cua10.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua11 ON cua11.id = hct.AllowanceID11 AND cua11.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua12 ON cua12.id = hct.AllowanceID12 AND cua12.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua13 ON cua13.id = hct.AllowanceID13 AND cua13.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua14 ON cua14.id = hct.AllowanceID14 AND cua14.IsDelete IS NULL
LEFT JOIN $select id from #Cat_UsualAllowance$ cua15 ON cua15.id = hct.AllowanceID15 AND cua15.IsDelete IS NULL
LEFT JOIN $select NameEntityName, id, IsDelete, OtherName from Cat_NameEntity$ cne ON cne.id=hp.EducationLevelID AND cne.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cne1 on cne1.ID=hp.GraduatedLevelID AND cne1.IsDelete IS NULL
LEFT JOIN $select NameEntityName, id, IsDelete from Cat_NameEntity$ cne2 ON cne2.id = hp.CostSourceID AND cne2.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cne3 ON cne3.id = hp.VehicleID AND cne3.IsDelete IS NULL
LEFT JOIN $select id, isdelete, PayrollGroupName, Code from Cat_PayrollGroup$ cpg ON cpg.id = hct.PayrollGroupID AND cpg.IsDelete IS NULL
LEFT JOIN $select RegionName, id, IsDelete from Cat_Region$ crio on hp.RegionID = crio.ID AND crio.IsDelete IS NULL
LEFT JOIN $select NameEntityName, id, IsDelete from Cat_NameEntity$ EmployeeGroup ON EmployeeGroup.id = hct.EmployeeGroupID and EmployeeGroup.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cne5 ON cne5.id = hct.ReasonChangeSalaryID AND cne5.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cne6 ON cne6.id = hct.ReasonChangeSalaryID2 AND cne6.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cne7 ON cne7.id = hct.DelegationReasonID AND cne7.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cne50  ON cne50.id = hct.DelegationReasonID2 AND cne50.IsDelete IS NULL
LEFT JOIN $select id, isdelete, EmployeeTypeName from Cat_EmployeeType$ cet ON cet.id = hct.EmployeeTypeID AND cet.IsDelete IS NULL
left join $select id, isdelete, ProfileName from Hre_Profile$ hp2 on hp2.ID = hp.SupervisorID and hp2.IsDelete IS NULL
left join $select id, isdelete, ProfileName from Hre_Profile$ highSup on highSup.ID = hp.highSupervisorID and highSup.IsDelete IS NULL
LEFT JOIN $select id, isdelete, ResignReasonName from Cat_ResignReason$ crr ON hp.ResReasonID=crr.ID AND crr.IsDelete IS NULL
LEFT JOIN $select id, isdelete, CountryName, CountryNameES from Cat_Country$ ccy ON hp.NationalityID = ccy.id AND ccy.IsDelete IS NULL
LEFT JOIN $select id, isdelete, CountryName, CountryNameES from Cat_Country$ ccy1 on ccy1.ID = hct.TCountryID AND ccy1.IsDelete IS NULL
LEFT JOIN $select id, isdelete, CountryName, CountryNameES from Cat_Country$ ccy2 on ccy2.ID = hct.PCountryID AND ccy2.IsDelete IS NULL
LEFT JOIN $select id, isdelete, ProvinceName from Cat_Province$ cp1 on cp1.ID = hct.TProvinceID AND cp1.IsDelete IS NULL
LEFT JOIN $select id, isdelete, DistrictName from Cat_District$ cd1 on cd1.ID = hct.TDistrictID AND cd1.IsDelete IS NULL
LEFT JOIN $select id, isdelete, VillageName from Cat_Village$ cv1 on cv1.ID = hct.TAVillageID AND cv1.IsDelete IS NULL
LEFT JOIN $select id, isdelete, OrgStructureName, code, OrderNumber from Cat_OrgStructure$ co1 ON co.ParentID = co1.id AND co1.IsDelete IS NULL
left join $select id, isdelete, orgstructureid ,Info1,Info2,Info3,Info4,Info5,Info6,Info7,Info8,Info9,Info10,Info11,Info12,Info13,Info14 from Cat_OtherInfoOrg$ coio on coio.orgstructureid = co.ID and coio.isdelete is null
LEFT JOIN $select id, isdelete, JobTitleName, JobtitleNameEn from Cat_JobTitle$ cj1 ON hp1.JobTitleID = cj1.id AND cj1.IsDelete IS NULL
LEFT JOIN $select id, isdelete, PositionName, PositionEngName from Cat_Position$ cp11 ON hp1.PositionID = cp11.id AND cp11.IsDelete IS NULL
LEFT JOIN $select id, isdelete, CountryName, CountryNameES from Cat_Country$ ccty ON hp1.NationalityID = ccty.ID AND ccty.IsDelete IS NULL
LEFT JOIN $select id, isdelete, ProvinceName from Cat_Province$ cpprosing on cpprosing.ID = hp1.PprovinceID AND cpprosing.IsDelete IS NULL
LEFT JOIN $select id, isdelete, DistrictName from Cat_District$ cdprosing on cdprosing.ID = hp1.PdistrictID AND cdprosing.IsDelete IS NULL
LEFT JOIN $select id, isdelete, VillageName from Cat_Village$ cvprosing on cvprosing.ID = hp1.VillageID AND cvprosing.IsDelete IS NULL
LEFT JOIN $select id, isdelete, BillingAddress,TelePhone,OrgStructureID from Cat_OrgMoreInfor$ cmibranch on cmibranch.OrgStructureID = $dbo.GETNEARESTPARENTID $hct.OrgStructureID,''E_BRANCH''$$ AND cmibranch.IsDelete IS NULL
LEFT JOIN $select id, isdelete, BillingAddress,TelePhone, OrgStructureID from Cat_OrgMoreInfor$ orgCompany on orgCompany.OrgStructureID = $dbo.GETNEARESTPARENTID $hct.OrgStructureID,''E_COMPANY''$$ AND orgCompany.IsDelete IS NULL
LEFT JOIN $select id, isdelete, CompanyID, ProfileID, NoDecision from Cat_DelegateCompany$ Delegate ON Delegate.id = hct.DelegateCompanyID AND Delegate.IsDelete IS NULL
left join $select id, isdelete, profileName, IDno, idplaceofissue, iddateofissue, positionid from hre_profile$ DelegatePro on DelegatePro.id = Delegate.ProfileID and DelegatePro.isdelete is null
LEFT JOIN $select id, isdelete, PositionName from Cat_Position$ DelegatePos ON DelegatePro.PositionID = DelegatePos.id AND DelegatePos.IsDelete IS NULL
LEFT JOIN $select id, isdelete, GradeAttendanceName, Code from Cat_GradeAttendance$ cga on cga.ID = hct.GradeAttendanceID AND cga.IsDelete is null
LEFT JOIN $select id, isdelete, TemplateName from eva_performanceTemplate$ performanceTemplate on performanceTemplate.id = hct.EvaPerformanceTemplateID and performanceTemplate.isdelete is null
LEFT JOIN $select id, isdelete, JobTitleName,Notes,JobTitleNameEn,Code from Cat_JobTitle$ contractJob on contractJob.id = hct.JobTitleID and contractJob.isdelete is null
LEFT JOIN $select id, isdelete, CostCentreName from Cat_CostCentre$ ccc1 on ccc1.id = hct.CostCentreID and ccc1.isdelete is null
LEFT JOIN $select id, isdelete, WorkPlaceName from Cat_WorkPlace$ cw1 on cw1.id = hct.WorkPlaceID  and cw1.isdelete is null
LEFT JOIN $select id, isdelete, PositionName, Code, PositionEngName, NumberOfChangeJobDescription,EffectiveDateOfDescription,ParentPositionID from Cat_Position$ contractPos on contractPos.id = hct.PositionID and contractPos.isdelete is null
LEFT JOIN $select id, isdelete, PositionName from Cat_Position$ contractPosParent on contractPosParent.id = contractPos.ParentPositionID and contractPosParent.isdelete is null
LEFT JOIN $select id, isdelete, UnitName, UnitCode from Cat_UnitStructure$ cust on cust.id = hct.UnitStructureID AND cust.IsDelete Is NULL
LEFT JOIN $select id,NationalityGroupID, isdelete, ProfileName,PositionID from Hre_Profile$ hpl ON hpl.id = hct.ProfileID AND hpl.IsDelete IS NULL
LEFT JOIN $select id, isdelete, PositionOtherName, Requirement,Permission,TaskLongTerm,TaskShortTerm from Cat_Position$ cpt ON hpl.PositionID = cpt.id AND cpt.IsDelete IS NULL
LEFT JOIN Hre_ProfileMoreInfo hpmi ON hpmi.id=hp.ProfileMoreInfoID AND hpmi.IsDelete IS NULL
left join $select id, isdelete, NameEntityName from Cat_NameEntity$ cne10 on cne10.ID = hpl.NationalityGroupID and cne10.IsDelete IS NULL
LEFT JOIN $select id from #Cat_Currency$ curkpi ON curkpi.id = hct.CurrencyKPIID AND curkpi.IsDelete IS NULL
LEFT JOIN $select id, isdelete,KPIRankName from cat_kpirank$ kpirank ON kpirank.id = hct.kpirankID AND kpirank.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cn ON cn.id = hct.DistributionChannelIDAND cn.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cn1 ON cn1.id = hct.MarketDomainID AND cn1.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cn2 ON cn2.id = hct.RegionMarketID AND cn2.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cn3 ON cn3.id = hct.MarketAreaID AND cn3.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity$ cn4 ON cn4.id = hct.OriginalDistributorID AND cn4.IsDelete IS NULL
LEFT JOIN $select id, isdelete, ProvinceName from dbo.Cat_Province$ hpmiProvince ON hpmiProvince.id = hpmi.ProvinceBirthCertificateID AND hpmiProvince.IsDelete IS NULL
LEFT JOIN $select id, isdelete, DistrictName from dbo.Cat_District$ hpmiDistrict ON hpmiDistrict.id = hpmi.DistrictBirthCertificateID AND hpmiDistrict.IsDelete IS NULL
LEFT JOIN $select id, isdelete, VillageName from dbo.Cat_Village$ hpmiVillage ON hpmiVillage.id = hpmi.VillageBirthCertificateID AND hpmiVillage.IsDelete IS NULL
LEFT JOIN $select UsualAllowanceGroupName, id, IsDelete from Cat_UsualAllowanceGroup$ cuap ON cuap.id = hct.UsualAllowanceGroupID AND cuap.IsDelete IS NULL
LEFT JOIN $select id from #Cat_Currency$ curtotal ON curtotal.id = hct.TotalSalaryCurrencyID AND curtotal.IsDelete IS NULL
LEFT JOIN $select id from #Cat_Currency$ curtotal2 ON curtotal2.id = hct.TotalAllowanceCurrencyID AND curtotal2.IsDelete IS NULL
Left JOIN #tblEnumChairmanGenderView cgv ON cgv.EnumKey = ccp.ChairmanGender
Left JOIN #tblEnumPITFormulaTypeView ptv ON ptv.EnumKey = Temp.PITCode
Left JOIN #tblEnumStatusView sv ON sv.EnumKey = hct.Status
Left JOIN #tblEnumContractView scv ON scv.EnumKey = hct.ContractEvaType
Left JOIN #tblEnumTypeOfPass tofp ON tofp.EnumKey = hct.TypeOfPass
Left JOIN #tblEnumUnitTypeView utv ON utv.EnumKey = hct.UnitTime
Left JOIN $select id from #tblEnumUnitTypeView$ utv3 ON utv3.EnumKey = hct.ProbationTimeUnit
Left JOIN #tblEnumTypeContractView tcv ON tcv.EnumKey = cc.Type
Left JOIN #tblEnumGenderViewNew egv ON egv.EnumKey = hp.Gender
Left JOIN #tblEnumStatusSynView ssv ON ssv.EnumKey = hp.StatusSyn
LEFT JOIN #tblEnumContractStatusView csv ON csv.EnumKey = hct.ContractStatus
left join #tblEnumStatusEvaluationView sev ON sev.EnumKey = hct.StatusEvaluation
LEFT JOIN #tblEnumWorkTimeInWeekType EnumWorkTimeInWeekType ON EnumWorkTimeInWeekType.EnumKey = hct.WorkTimeInWeek
LEFT JOIN #tblEnumCalendarWorkType EnumCalendarWorkType ON EnumCalendarWorkType.EnumKey = hct.CalendarWork
LEFT JOIN #tblEnumWeeklyLeaveDayType EnumWeeklyLeaveDayType ON EnumWeeklyLeaveDayType.EnumKey = hct.WeeklyLeaveDay
LEFT JOIN #tblEnumSignatureDigitalStatus SignatureDigitalStatus ON SignatureDigitalStatus.EnumKey = hct.StatusEmailSignatureDigital
Left JOIN #tblEnumLaborType lt ON lt.EnumKey = hct.LaborType
LEFT JOIN $select id, isdelete, CountryName from Cat_Country$ contractTCountry ON contractTCountry.ID = hct.TCountryID AND contractTCountry.IsDelete IS NULL
LEFT JOIN $select id, isdelete, ProvinceName from Cat_Province$ contractTProvince ON contractTProvince.ID = hct.TProvinceID AND contractTProvince.IsDelete IS NULL
LEFT JOIN $select id, isdelete, DistrictName from Cat_District$ contractTDistrict ON contractTDistrict.ID = hct.TDistrictID AND contractTDistrict.IsDelete IS NULL
LEFT JOIN $select id, isdelete, VillageName from Cat_Village$ contractTVillage ON contractTVillage.ID = hct.TAVillageID AND contractTVillage.IsDelete IS NULL
LEFT JOIN $select id, isdelete, OriginID,WorkPlaceName  from Cat_WorkPlace_Translate$ cawt ON cawt.OriginID = hct.WorkPlaceID AND cawt.IsDelete IS NULL
LEFT JOIN $select id, isdelete,ProfileSingID,ContractID,WorkPlaceID, AbilityTileID, Note2 ,Note, EmployeeGroupSecondDetailID, EmployeeGroupFirstDetailID from #tblContractExtend$ hce ON hce.ContractID = hct.ID AND hce.IsDelete IS NULL
LEFT JOIN $select id, isdelete,ProfileName,NameEnglish,PositionID from Hre_Profile$ exPro ON exPro.ID = hce.ProfileSingID AND exPro.IsDelete IS NULL
LEFT JOIN $select id, isdelete,PositionName,PositionEngName  from Cat_Position$ exPos ON exPos.ID = exPro.PositionID AND exPos.IsDelete IS NULL
LEFT JOIN $select id, isdelete,WorkPlaceName, OriginID  from Cat_WorkPlace_Translate$ exwl ON exwl.OriginID = hce.WorkPlaceID AND exwl.IsDelete IS NULL
LEFT JOIN $select id, isdelete, AbilityTitleVNI,AbilityTitleEng from Cat_AbilityTile$ cat2 ON cat2.id = hce.AbilityTileID AND cat2.IsDelete IS NULL
LEFT JOIN $select id, isdelete, ProvinceName, ProvinceNameEN from Cat_Province$ cp2 on cp2.ID = hct.PProvinceID AND cp2.IsDelete IS NULL
LEFT JOIN $select id, isdelete, DistrictName, DistrictNameEN from Cat_District$ cd2 on cd2.ID = hct.PDistrictID AND cd2.IsDelete IS NULL
LEFT JOIN $select id, isdelete, VillageName,VillageNameEN from Cat_Village$ cv2 on cv2.ID = hp.VillageID AND cv2.IsDelete IS NULL
LEFT JOIN $select id, isdelete, OriginID,SalaryClassName  from Cat_SalaryClass_Translate$ slary ON slary.OriginID = hp.SalaryClassID AND slary.IsDelete IS NULL
LEFT JOIN $select id, isdelete,ProfileID from Sys_UserInfo$ ssreject ON ssreject.id = hct.UserRejectID AND ssreject.IsDelete IS NULL
LEFT JOIN $select id, isdelete,ProfileName from Hre_Profile$ hpreject ON hpreject.id = ssreject.ProfileID AND hpreject.IsDelete IS NULL
LEFT JOIN $select id, isdelete,ProfileID from Sys_UserInfo$ sscancel ON sscancel.id = hct.UserCancelID AND sscancel.IsDelete IS NULL
LEFT JOIN $select id, isdelete,ProfileName from Hre_Profile$ hpcancel ON hpcancel.id = sscancel.ProfileID AND hpcancel.IsDelete IS NULL
left join $select id, isdelete,ContractTypeName from Cat_ContractType$ cct  ON hct.NextContractTypeID = cct.id AND cct.IsDelete IS NULL
left join $select id from Cat_EmpGroupSecondDetail$ cegsd2  ON hct.EmployeeGroupSecondDetailID = cegsd2.id AND cegsd2.IsDelete IS NULL
left join $select id from Cat_EmpGroupFirstDetail$ cegfd1  ON hct.EmployeeGroupFirstDetailID = cegfd1.id AND cegfd1.IsDelete IS NULL
LEFT JOIN $select id from Cat_Province$ cpPlaceOfIssue ON cpPlaceOfIssue.id = hct.PlaceOfIssueID AND cpPlaceOfIssue.IsDelete IS NULL
LEFT JOIN Cat_IDCardIssuePlace cpIDCardIssuePlace ON cpIDCardIssuePlace.id = hct.IDCardIssuePlaceID AND cpIDCardIssuePlace.IsDelete IS NULL
LEFT JOIN Cat_PassportIssuePlace cpPassportPlace ON cpPassportPlace.id = hct.PassportPlaceID AND cpPassportPlace.IsDelete IS NULL
left join Cat_EmpGroupSecondDetail cegsd4  ON hce.EmployeeGroupSecondDetailID = cegsd4.id AND cegsd4.IsDelete IS NULL
left join Cat_EmpGroupFirstDetail cegfd3  ON hce.EmployeeGroupFirstDetailID = cegfd3.id AND cegfd3.IsDelete IS NULL
LEFT JOIN $select id, isdelete,ProfileName from Hre_Profile$ PersonCancellation ON PersonCancellation.id = hct.PersonCancellationID AND PersonCancellation.IsDelete IS NULL
LEFT JOIN #tblEnumStatusCancelDigitalSignature statusCancelDigitalSignature ON statusCancelDigitalSignature.EnumKey = hct.StatusCancelDigitalSignature
left join #tblProfileQualification proqua on proqua.ProfileID = hct.ProfileID
LEFT JOIN $select id, isdelete, VillageName,VillageNameEN from Cat_Village$ cv22 on cv22.ID = hct.PVillageID AND cv22.IsDelete IS NULL
LEFT JOIN Cat_NameEntity cnea ON cnea.id = hct.DigitalSignatureCodeID AND cnea.IsDelete IS NULL
LEFT JOIN $select id, isdelete, NameEntityName from Cat_NameEntity where IsDelete  IS NULL$ cn5  ON cn5.id = hct.CostSourceID