-- test store 

--format 
--	System_SP_Select       [SPCode], [TableName], [ColumnName], [ColumnAlias], [ColumnQuery]
--  System_sp_tablelinks   [SPCode], [TableName], [TableAlias], [Order], [JointTable], [JointTableColumn], [LinkedTableColumn], [JointType], [ExtraConditions], [CustomQuery], [IsRequired]

EXEC KAIZEN_STORE 
@ClauseSelect = N'$al.*,$al.Test2,$hp.ProfileName,$hp.OrgStructureID,$hp.CodeEmp,$co.OrgStructureName,$ct.TAMScanReasonMissName,$cp."PositionName",$cjt."JobTitleName",$su.UserInfoName AS UserApproveName,$hp1.ImagePath AS AvatarUserApprove1,$su1.UserInfoName AS UserApproveName2,$hp2.ImagePath AS AvatarUserApprove4,$su3.UserInfoName AS UserApproveName3,$hp3.ImagePath AS AvatarUserApprove2,$su4.UserInfoName AS UserApproveName4,$hp4.ImagePath AS AvatarUserApprove3,$cou.E_COMPANY,$cou.E_BRANCH,$cou.E_UNIT,$cou.E_DIVISION,$cou.E_DEPARTMENT,$cou.E_TEAM,$cou.E_SECTION,$cou.E_OU_L8,$cou.E_OU_L9,$cou.E_OU_L10,$cou.E_OU_L11,$cou.E_OU_L12,$cou.E_COMPANY_CODE,$cou.E_BRANCH_CODE,$cou.E_UNIT_CODE,$cou.E_DIVISION_CODE,$cou.E_DEPARTMENT_CODE,$cou.E_TEAM_CODE,$cou.E_SECTION_CODE,$cou.E_OU_L8_CODE,$cou.E_OU_L9_CODE,$cou.E_OU_L10_CODE,$cou.E_OU_L11_CODE,$cou.E_OU_L12_CODE,$al.FileAttachment +''|''+ al.UserCreate as FileAttachmentView,$sts.EnumTranslate AS "StatusView",$tv.EnumTranslate AS TypeView,$cjt.JobTitleName,$cp.PositionName,$cwp2.WorkPlaceName,$cc.CompanyName,$cwf.WifiName AS WifiNameView,$cwf.Code AS WifiCode,$al.IsCheckApp,$al.IsPayback AS IsPayBackView,$su5.UserInfoName AS UserReject,$hp5.ImagePath AS AvatarUserRejected,$su6.UserInfoName as UserCancelName,$hp6.ImagePath AS AvatarUserCancel,$cwp3.WorkPlaceName AS PlaceName',
@ClauseFrom = N'*Att_TamScanLogRegister al*INNER JOIN "Hre_Profile" hp ON al.ProfileID = hp.Id AND hp."IsDelete" IS NULL*LEFT JOIN "Cat_Position" cp ON hp."PositionID" = cp."ID" AND cp."IsDelete" IS NULL*LEFT JOIN "Cat_JobTitle" cjt ON hp."JobTitleID" = cjt."ID" AND cjt."IsDelete" IS NULL*left join $select ID from Sys_UserInfo$ su ON al.UserApproveID = su.Id AND su."IsDelete" IS NULL*LEFT JOIN $select ID from Hre_Profile$ hp1 ON hp1.ID = su.ProfileID AND hp1.IsDelete IS NULL*left join $select ID from Sys_UserInfo$ su1 ON al.UserApproveID2 = su1.Id AND su1."IsDelete" IS NULL*LEFT JOIN $select ID from Hre_Profile$ hp2 ON hp2.ID = su1.ProfileID AND hp2.IsDelete IS NULL*left join $select ID from Sys_UserInfo$ su3 ON al.UserApproveID3 = su3.Id AND su3."IsDelete" IS NULL*LEFT JOIN $select ID from Hre_Profile$ hp3 ON hp3.ID = su3.ProfileID AND hp3.IsDelete IS NULL*left join $select ID from Sys_UserInfo$ su4 ON al.UserApproveID4 = su4.Id AND su4."IsDelete" IS NULL*LEFT JOIN $select ID from Hre_Profile$ hp4 ON hp4.ID = su4.ProfileID AND hp4.IsDelete IS NULL*left join Cat_OrgStructure co ON al.OrgStructureID = co.Id AND co."IsDelete" IS NULL*LEFT JOIN Cat_TAMScanReasonMiss ct ON al.MissInOutReason = ct.ID AND ct.IsDelete IS NULL*left join Cat_OrgUnit cou ON hp.OrgstructureID = cou.OrgstructureID AND cou."IsDelete" IS NULL*left join Cat_Company cc on cc.ID = al.CompanyID and cc.IsDelete is null*LEFT JOIN "Cat_WorkPlace" cwp2 ON al.WorkPlaceID = cwp2."ID" AND cwp2."IsDelete" IS NULL*LEFT JOIN Cat_Wifi cwf ON cwf.ID = al.WifiID AND cwf.IsDelete IS NULL*LEFT JOIN $select ID from Sys_UserInfo$ su5 ON al.UserRejectID = su5.Id AND su5."IsDelete" IS NULL*LEFT JOIN $select ID from Hre_Profile$ hp5 ON hp5.ID = su5.ProfileID AND hp5.IsDelete IS NULL*LEFT JOIN $select ID from Sys_UserInfo$ su6 ON al.UserCanelID = su6.Id AND su6."IsDelete" IS NULL*LEFT JOIN $select ID from Hre_Profile$ hp6 ON hp6.ID = su6.ProfileID AND hp6.IsDelete IS NULL*LEFT JOIN #tblEnumStatusView sts ON sts.EnumKey = al.Status*LEFT JOIN #tblEnumTypeView tv ON tv.EnumKey = al.Type*LEFT JOIN "Cat_WorkPlace" cwp3  ON al.PlaceID = cwp3."ID" AND cwp3."IsDelete" IS NULL'


